Repository Pure-Farming/Documentation, pull requests merged in 2022-12, with the labels that each got.

#20 Feat streaming api
  docs/connected-data.md
  docs/resource-types/index.md
  docs/streaming-api/changes.md
  docs/streaming-api/control.md
  docs/streaming-api/datasets.md
  docs/streaming-api/index.md
  docs/streaming-api/resources.md
Labels: documentation, enhancement

#19 feat: add group weight event documentation
  docs/resource-types/index.md
  docs/resource-types/livestock/common.md
  docs/resource-types/livestock/index.md
  docs/resource-types/livestock/treatments/group-treament-event.md
  docs/resource-types/livestock/weights/group-weight-event.md
  docs/resource-types/livestock/weights/index.md
Labels: documentation

#21 fix(streaming): supported resource types link
  docs/streaming-api/control.md
  docs/streaming-api/index.md
  docs/streaming-api/resources.md
Labels: bug, documentation

#22 Fix livestock weights link
  docs/resource-types/index.md
  docs/resource-types/livestock/weights/index.md
Labels: bug

#23 fix: livestock treatments link
  docs/resource-types/livestock/animals.md
  docs/resource-types/livestock/index.md
Labels: bug
